services:
  backend:
    container_name: backend
    build: .
    volumes: 
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: always
    