"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import ssl
from datetime import timedelta
from pathlib import Path
from urllib.parse import quote

from celery.schedules import crontab
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=lambda v: [s.strip() for s in v.split(",")],
)

# django.contrib.sites -- backs the Sitemap/RSS-feed absolute-URL
# resolution (django.contrib.sitemaps and django.contrib.syndication
# both build links from the current Site's domain). The domain/display
# name are read from the environment so nothing is hardcoded here; the
# defaults below only apply to a bare local dev checkout with no .env
# override, and are written into the Site row by the
# website 0005_configure_site data migration.
SITE_ID = 1
SITE_DOMAIN = config("SITE_DOMAIN", default="localhost:8000")
SITE_DISPLAY_NAME = config("SITE_DISPLAY_NAME", default="Nexora (Local)")

# Mapbox access token used by the Leaflet map on the contact page
# (core/website/views.py ContactView -> templates/website/page-contact.html
# -> static/js/plugins/leaflet.js). Read from the environment only --
# never hardcode a real token in source (see .env.example). Empty by
# default so a bare checkout with no .env still boots; the map tiles
# just will not load without a real token configured.
MAPBOX_ACCESS_TOKEN = config("MAPBOX_ACCESS_TOKEN", default="")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    # Third-party
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "drf_spectacular",
    # My app
    "accounts",
    "website",
    "blog",
    "shop",
    "vendors",
    "cart",
    "orders",
    "dashboard",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.site_locale",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(
            config("DATABASE_PATH", default=str(BASE_DIR / "db.sqlite3"))
        ),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# The storefront's only supported currency. Every price in the
# database (Product.price, cart/order totals, etc.) is a plain
# DecimalField denominated in this currency -- there is no per-item
# currency field or conversion table, so this is the single source
# of truth the header's Currency indicator (see
# core.context_processors.site_locale) reads from. Introducing a
# second currency would require a real conversion/rounding source
# and currency-aware fields on Product/Cart/Order first.
DEFAULT_CURRENCY = "USD"
DEFAULT_CURRENCY_SYMBOL = "$"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# User manage config
AUTH_USER_MODEL = "accounts.CustomUser"

# Email (used for the account-verification and password-reset links).
# Credentials are read only from the environment/`.env` -- never hardcoded.
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587

EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
# Seconds before an SMTP connection/command gives up. Django's default is
# "no timeout", which lets a stalled mail server pin a Celery worker slot
# forever; with a timeout the task fails fast and is retried (see
# accounts.tasks).
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=10, cast=int)

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# Redis
# Connection details are read from the environment/`.env` only -- never
# hardcode a host or credential here (see .env.example). They are used by
# core.redis_client (health check, email-task idempotency markers) and to
# build the Celery broker URL below. The defaults suit a bare local
# checkout with a Redis on localhost; under Docker Compose the backend and
# worker services set REDIS_HOST=redis (the Redis service name).
REDIS_HOST = config("REDIS_HOST", default="localhost")
REDIS_PORT = config("REDIS_PORT", default=6379, cast=int)
REDIS_DB = config("REDIS_DB", default=0, cast=int)
# Empty means "no authentication" -- acceptable for local dev only;
# docker-compose.prod.yml refuses to start without a password.
REDIS_PASSWORD = config("REDIS_PASSWORD", default="")
REDIS_SSL = config("REDIS_SSL", default=False, cast=bool)
# Short timeouts so an unreachable Redis is reported quickly instead of
# hanging a request or a health check.
REDIS_SOCKET_CONNECT_TIMEOUT = config(
    "REDIS_SOCKET_CONNECT_TIMEOUT", default=2.0, cast=float
)
REDIS_SOCKET_TIMEOUT = config("REDIS_SOCKET_TIMEOUT", default=2.0, cast=float)

# Celery (background jobs)
# The broker is the same Redis service configured above, on its own logical
# database (REDIS_BROKER_DB) so queue keys never mix with anything else
# stored in DB 0. CELERY_BROKER_URL can be set to override the derived URL.
# There is deliberately NO result backend and results are ignored: tasks
# return None, so no password / OTP / reset token is ever kept as a result.
REDIS_BROKER_DB = config("REDIS_BROKER_DB", default=1, cast=int)
_redis_scheme = "rediss" if REDIS_SSL else "redis"
_redis_auth = f":{quote(REDIS_PASSWORD, safe='')}@" if REDIS_PASSWORD else ""
CELERY_BROKER_URL = config(
    "CELERY_BROKER_URL",
    default=(
        f"{_redis_scheme}://{_redis_auth}{REDIS_HOST}:{REDIS_PORT}"
        f"/{REDIS_BROKER_DB}"
    ),
)
if REDIS_SSL:
    CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_REQUIRED}

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_IGNORE_RESULT = True

# At-least-once delivery: a task is acknowledged only after it finishes, so
# a worker that dies mid-task hands it back to the queue. Every task must
# therefore be idempotent (see accounts.tasks).
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# Hard stops for a task stuck on the network (soft raises inside the task
# first so it can be retried; the hard limit kills it).
CELERY_TASK_SOFT_TIME_LIMIT = 60
CELERY_TASK_TIME_LIMIT = 90

# Start the worker even if Redis is not accepting connections yet; it
# keeps retrying instead of exiting.
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Publishing (done by the web process) must never hang a request: keep the
# connect timeout short and give up after a couple of quick retries. The
# caller decides what to do when the enqueue fails (see accounts.otp).
CELERY_BROKER_CONNECTION_TIMEOUT = REDIS_SOCKET_CONNECT_TIMEOUT
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": 3600,
    "socket_connect_timeout": REDIS_SOCKET_CONNECT_TIMEOUT,
}
CELERY_TASK_PUBLISH_RETRY = True
CELERY_TASK_PUBLISH_RETRY_POLICY = {
    "max_retries": 2,
    "interval_start": 0,
    "interval_step": 0.2,
    "interval_max": 0.5,
}

# Run tasks inline in the calling process instead of sending them to the
# broker. The test suite turns this on itself (core/conftest.py); it can
# also be handy for a local run without Redis/worker. Never enable it in
# production: it puts SMTP back inside the request.
CELERY_TASK_ALWAYS_EAGER = config(
    "CELERY_TASK_ALWAYS_EAGER", default=False, cast=bool
)
CELERY_TASK_EAGER_PROPAGATES = True

# Celery Beat (scheduled jobs)
# Beat is a separate process (`celery -A core beat`, the `beat` service in
# docker-compose*.yml); exactly ONE must run, otherwise every job would be
# dispatched once per beat. Crontab times are read in CELERY_TIMEZONE, which
# follows the project's TIME_ZONE.
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
# Without a result backend there is nothing to expire. Celery would still
# add its own daily "celery.backend_cleanup" entry to the schedule when
# result_expires is set (it is by default); None keeps the schedule to
# exactly the jobs listed below.
CELERY_RESULT_EXPIRES = None
# Only clean-ups of data that would otherwise pile up forever -- see
# accounts/maintenance.py for what each one removes and why. Once a day,
# off-peak, staggered so they never overlap. `expires` drops a dispatched
# run that no worker picked up within 6 hours (e.g. the worker was down),
# so a backlog of stale runs cannot pile up and fire all at once later;
# the next day's run simply takes over.
CELERY_BEAT_SCHEDULE = {
    "cleanup-expired-otp-codes": {
        "task": "accounts.cleanup_expired_otp_codes",
        "schedule": crontab(hour=3, minute=15),
        "options": {"expires": 6 * 60 * 60},
    },
    "cleanup-expired-sessions": {
        "task": "accounts.cleanup_expired_sessions",
        "schedule": crontab(hour=3, minute=30),
        "options": {"expires": 6 * 60 * 60},
    },
    "cleanup-expired-jwt-tokens": {
        "task": "accounts.cleanup_expired_jwt_tokens",
        "schedule": crontab(hour=3, minute=45),
        "options": {"expires": 6 * 60 * 60},
    },
}

# Django REST Framework
# The frontend is a server-rendered site with fetch()-based AJAX calls
# from the same origin, authenticated with the existing Django
# session/cookie. Alongside that, a stateless JWT surface (see
# api.v1.views.auth_jwt / POST /api/v1/auth/token/) is available for
# the API/other (non-browser) clients -- both authentication schemes
# are accepted on every endpoint.
REST_FRAMEWORK = {
    # JWTAuthentication first: DRF's 401-vs-403 fallback (APIView.
    # handle_exception) only looks at the *first* configured
    # authenticator's WWW-Authenticate header when deciding whether an
    # unauthenticated/invalid request gets 401 or 403.
    # SessionAuthentication doesn't provide one, so if it were listed
    # first every unauthenticated request -- JWT or session alike --
    # would incorrectly get downgraded to 403.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_PAGINATION_CLASS": "api.v1.pagination.StandardPagination",
    "PAGE_SIZE": 12,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ]
    + (["rest_framework.renderers.BrowsableAPIRenderer"] if DEBUG else []),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# djangorestframework-simplejwt -- backs the stateless JWT auth surface
# (POST /api/v1/auth/token/, .../refresh/, .../verify/). Access tokens
# are short-lived; refresh tokens rotate on use and the token that was
# just used is blacklisted, so a leaked/stolen refresh token can't be
# replayed after its holder (or an attacker who captured it) uses it
# once. This requires rest_framework_simplejwt.token_blacklist in
# INSTALLED_APPS (see above) -- without it, RefreshToken.for_user()
# still tries to record an outstanding-token row internally and blows
# up with "OutstandingToken has no attribute 'objects'", since that
# model is only a real (non-abstract) table when the app is installed.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# drf-spectacular (OpenAPI / Swagger / Redoc)
# https://drf-spectacular.readthedocs.io/en/latest/settings.html
SPECTACULAR_SETTINGS = {
    "TITLE": "Nexora API",
    "DESCRIPTION": (
        "Official REST API for the Nexora multi-vendor grocery marketplace.\n\n"
        "The API is consumed by Nexora's own server-rendered frontend via "
        "same-origin fetch() calls, authenticated through the standard Django "
        "session cookie (see the `sessionid` and `csrftoken` cookies). "
        "To try authenticated endpoints from this page, log in through the "
        "site at `/accounts/login/` (or call `POST /api/v1/auth/login/`) in "
        "the same browser session first, then send the `X-CSRFToken` header "
        "with unsafe (POST/PATCH/PUT/DELETE) requests."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/v[0-9]+",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayRequestDuration": True,
    },
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": False,
    "TAGS": [
        {
            "name": "Auth",
            "description": "Registration, session login/logout and the current user's profile.",
        },
        {
            "name": "Catalog",
            "description": "Browsing categories, tags and products.",
        },
        {"name": "Reviews", "description": "Product reviews."},
        {"name": "Vendors", "description": "Marketplace vendors (sellers)."},
        {
            "name": "Wishlist",
            "description": "The current user's saved/favourite products.",
        },
        {
            "name": "Cart",
            "description": "The current user's shopping cart and its line items.",
        },
        {
            "name": "Addresses",
            "description": "The current user's shipping/billing addresses.",
        },
        {"name": "Coupons", "description": "Discount coupon validation."},
        {
            "name": "Orders",
            "description": "Checkout and the current user's order history.",
        },
    ],
}
