from django.conf import settings
from django.db import migrations
from django.utils.text import slugify


def create_missing_vendor_profiles(apps, schema_editor):
    """
    One-time data repair for accounts that ended up with role=Vendor
    but no Vendor row -- e.g. anyone who registered as a vendor before
    vendors.signals.create_vendor_profile_for_vendor_role existed.

    Historical migration models don't run Vendor.save()'s custom
    slug-from-store_name logic, so the slug is generated by hand here
    (with a numeric suffix on collision, since it's unique=True).
    """
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    Vendor = apps.get_model("vendors", "Vendor")

    for user in User.objects.filter(
        role="vendor", vendor_profile__isnull=True
    ):
        store_name = f"{user.username}'s Store"
        base_slug = slugify(store_name) or f"vendor-{user.pk}"
        slug = base_slug
        suffix = 2
        while Vendor.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{suffix}"
            suffix += 1
        Vendor.objects.create(user=user, store_name=store_name, slug=slug)


def noop(apps, schema_editor):
    # One-way data repair: rolling this back by deleting the created
    # Vendor rows could destroy real store data a vendor has since
    # filled in, so there's nothing safe to reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_missing_vendor_profiles, noop),
    ]
