# Generated by Django 5.2.14 on 2026-09-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="post",
            new_name="blog_post_status_02ce19_idx",
            old_name="blog_post_status_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="blog_post_slug_cdb902_idx",
            old_name="blog_post_slug_idx",
        ),
    ]
